version: '2'

services:

  gallery:
    build: galleryService
    depends_on:
      - 'database'
    ports:
      - '3003:3003'

  description:
    build: descriptionService
    depends_on:
      - 'database'
      - 'gallery'
    ports: 
      - '3001:3001'


  proxy:
    build: proxy
    depends_on:
      - 'gallery'
      - 'description'
    ports:
      - '3000:3000'    




 

  database:
    
    image: mongo:latest

